### ISSUE TITLE
Possibility to empty inbox thorugh api

### ISSUE THREAD

**Issue by ando0689** [rklf/yopmail#13]
It would be very cool to have an api through your library to empty the inbox of particular yopmail, if they allow this to be done through api. the problem is that sometimes we have emails with the same content, and we need to pick the one that was just sent, but due to the delay of receiving the email, we are getting the previous email. A functionality to clear the inbox will solve this issue.

**Comment by jasp402** [comment]
> It would be very cool to have an api through your library to empty the inbox of particular yopmail, if they allow this to be done through api. the problem is that sometimes we have emails with the same content, and we need to pick the one that was just sent, but due to the delay of receiving the email, we are getting the previous email. A functionality to clear the inbox will solve this issue.

Have you tried [Easy-yopmail](https://www.npmjs.com/package/easy-yopmail). It allows you to delete the inbox or a particular email. I know it's not made for Python but maybe it will help you.

**Comment by rklf** [comment]
You can now use `delete_mail()` method to delete a mail. You could loop through pages to empty inbox.

See #15.
