### ISSUE TITLE
Deletion of a mail using mail_id

### ISSUE THREAD

**Issue by hp-01** [rklf/yopmail#14]
This feature can be used to remove mail.

**Comment by hp-01** [comment]
I have the code for the deletion of mail can you teach me how to contribute it here.

**Comment by hp-01** [comment]
def delete_mail(self, mailid, page=1, proxies=None) -> requests.models.Response|None:
        params = {
            'login': self.username,
            'p': str(page), # page
            'd': mailid,        # mailid? to delete?
            'ctrl': '',     # mailid or ''
            'yp': self.yp,
            'yj': self.yj,
            'v': self.version,
            'r_c': '',      # '' or recaptcha? 
            'id': '',       # idaff / sometimes "none" / nextmailid='last' / mailid = id('m%d'%mail_nr)
            'ad': '0',       # 0 or 1 (advertising i guess)
            # 'scrl': '',
            # 'yf': '005',
        }
        return self.request(f'{self.url}inbox', params=params, proxies=proxies, context='inbox')

**Comment by rklf** [comment]
Merged by #15
