### ISSUE TITLE
get_mail_ids returns empty "[]"

### ISSUE THREAD

**Issue by pgranados0503** [rklf/yopmail#16]
Hi, I'm trying to read an email but get_mail_ids returns empty "[]"

Python version: 3.12.3
SO: Debian 12

My code:
```python
y = Yopmail(correo, proxies=None)
mails_id = y.get_mail_ids(page=1)
for mail_id in mails_id:
  mail = y.get_mail_body(mail_id, show_image=True)
  html_content = mail.html
```

**Comment by rklf** [comment]
Double-check you aren't rate-limited by Recaptcha (try to go on an inbox from browser and with same ip address)
